#!/bin/bash

RED='\033[0;31m'
NC='\033[0m'
GREEN='\033[0;32m'
DEVICE="WH-1000XM4"

remove_devices()
{
    if [ $(bluetoothctl show | grep Powered | awk '{print $2}') == "no" ]; then
        echo "Bluetooth is disabled"
        echo "Enabling Bluetooth..."
        bluetoothctl power on > /dev/null
    fi
    if [ $(bluetoothctl paired-devices | grep $DEVICE | wc -l) -eq 1 ]; then
        echo -e $GREEN"Device already paired"$NC
        return
    fi
    echo "Removing all paired devices..."
    paired_devices=$(bluetoothctl paired-devices | grep Device | awk '{print $2}')
    for device in $paired_devices; do
        bluetoothctl remove "$device" > /dev/null
    done
    echo -e $GREEN"All paired devices removed"$NC
}

connection()
{
    echo "Connecting to $DEVICE..."
    timeout 5 bluetoothctl scan on > /dev/null
    CASQUE=$(bluetoothctl devices | grep -w $DEVICE | awk '{print $2}')
    bluetoothctl connect $CASQUE > /dev/null
    if [ $? -ne 0 ]; then
        echo -e $RED"Failed to connect to WH-1000XM4"$NC
        exit 1
    fi
    echo -e $GREEN"-> Connected to WH-1000XM4"$NC
}

remove_devices
connection
