#!/bin/bash

# COLOR
RESET='\033[0m'
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
B_RED='\033[1;31m'

DUST_LINK=https://github.com/bootandy/dust/releases/download/v1.1.2/dust-v1.1.2-x86_64-unknown-linux-gnu.tar.gz
GUM_LINK=https://github.com/charmbracelet/gum/releases/download/v0.16.0/gum_0.16.0_Linux_x86_64.tar.gz
BYPASS_MODE=true
DELETE_DEPENDENCIES=false
CURRENT_DIR=$(pwd)

clear 
print_color() {
    local color=$1
    local message=$2
    case "$color" in
        "red") echo -e "${RED}${message}${RESET}" ;;
        "green") echo -e "${GREEN}${message}${RESET}" ;;
        "yellow") echo -e "${YELLOW}${message}${RESET}" ;;
        "blue") echo -e "${BLUE}${message}${RESET}" ;;
    esac
}

check_dependencies() {
    if ! command -v dust &> /dev/null; then
        print_color "red" "Error: 'dust' is not installed."
        print_color "blue" "Installing 'dust'..."

        wget -q $DUST_LINK -O /tmp/dust.tar.gz
        tar -xf /tmp/dust.tar.gz -C /tmp
        mv /tmp/dust-v1.1.2-x86_64-unknown-linux-gnu/dust ~/.local/bin

        if ! command -v dust &> /dev/null; then
            print_color "red" "Error: 'dust' installation failed."
            exit 1
        fi
        print_color "green" "'dust' has been successfully installed."
    fi

    if ! command -v gum &> /dev/null; then
        print_color "red" "Error: 'gum' is not installed."
        print_color "blue" "Installing 'gum'..."

        wget -q $GUM_LINK -O /tmp/gum.tar.gz
        tar -xf /tmp/gum.tar.gz -C /tmp
        mv /tmp/gum_0.16.0_Linux_x86_64/gum ~/.local/bin

        if ! command -v gum &> /dev/null; then
            print_color "red" "Error: 'gum' installation failed."
            exit 1
        fi
        print_color "green" "'gum' has been successfully installed."
    fi
}

bypass() {
	clear
	gum style --foreground 2 "Bypass mode enabled."
    export XDG_DATA_DIRS=$XDG_DATA_DIRS:$HOME/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/var/lib/snapd/desktop:$HOME/.local/share/applications
    gnome-session
}

storage_checker() {
    gum style --border normal --border-foreground 212 --margin "1" --padding "1 2" --bold "🧹 PC Storage Cleaner"
    total_size=$(dust ~ -z 100M -C | tail -n 1 | awk '{print $2}' | tr -cd '0-9.')

    if (( $(echo "$total_size > 5" | bc -l) )); then
        if [[ "$BYPASS_MODE" == true ]]; then
            gum style --foreground 1 "Total size is greater than 5G"
            gum style --foreground 3 "(${total_size}G)"
            bypass
        fi

        gum style --foreground 1 "Total size is greater than 5G" "(${total_size}G)"
        if gum confirm "Do you want to see your filesystem usage?"; then
            dust ~ -z 100M -C | gum pager
        fi

        if gum confirm "Do you want to launch the interactive shell to clean up files?"; then
            clear
            cd ~
            gum style --foreground 3 "Type 'exit' when done."
            gum style --foreground 3 "You can use 'dust' command to check storage usage."
            PS1="${GREEN}cleaner_shell>${RESET} " bash --norc
            cd "$CURRENT_DIR"
        fi

        total_size=$(dust ~ -z 100M -C | tail -n 1 | awk '{print $2}' | tr -cd '0-9.')

        if (( $(echo "$total_size > 5" | bc -l) )); then
            gum style --foreground 3 "Storage is still over 5GB (${total_size}G)"
            if gum confirm "Do you want to enable bypass_mode?"; then
                BYPASS_MODE=true
                bypass
            fi
        else
            gum style --foreground 2 "Great job! Storage is now under 5GB (${total_size}G)"
            gum style --foreground 3 "You can relog now."
        fi
    else
        gum style --foreground 2 "Total size is less than 5GB."
    fi
}

delete_dependencies() {
    if [[ "$DELETE_DEPENDENCIES" == true ]]; then
    gum style --foreground 3 "Deleting dependencies..."
    gum spin --spinner dot --title "Cleaning up..." -- bash -c "
        rm -rf /tmp/dust-v1.1.2-x86_64-unknown-linux-gnu /tmp/gum_0.16.0_Linux_x86_64
        rm -rf /tmp/dust.tar.gz /tmp/gum.tar.gz
        rm -rf ~/.local/bin/dust ~/.local/bin/gum
    "
    gum style --foreground 2 "Dependencies have been deleted."
    fi
}

main() {
    check_dependencies
    storage_checker
    delete_dependencies
}


main
